version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # Adjust based on your server port
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
