apiVersion: v1
kind: Service
metadata:
  name: mern-service
spec:
  selector:
    app: mern-app
  ports:
    - protocol: TCP
      port: 80            # External port
      targetPort: 3000    # Internal app port
  type: LoadBalancer      # Options: ClusterIP, NodePort, LoadBalancer
